### ISSUE TITLE
パターンA：縦スクロール版デザイン

### ISSUE THREAD

**Issue by AndreTakeshiOnaga** [TAKESHI-ONAGA/New#3]
ヘッダーにロゴとメニュー、WORKSの画像を縦に並べる。フッターを用意して会社情報などを載せたデザイン。

**Comment by Takeshionaga** [comment]
その後、どうですか。
#画像を貼ってください！

**Comment by AndreTakeshiOnaga** [comment]
![qljznwt3](https://cloud.githubusercontent.com/assets/28382243/25733636/34fbb226-3196-11e7-823f-e98293c4791c.jpeg)

**Comment by Takeshionaga** [comment]
ピカチュウです。
![pika](https://cloud.githubusercontent.com/assets/20039854/25733691/e4c21eca-3196-11e7-8369-b64d35632e46.jpg)

**Comment by Takeshionaga** [comment]
完了です。ありがとうございました

**Comment by AndreTakeshiOnaga** [comment]
こちらこそ
